### PR TITLE
Laravel 9 upgrade

### LINKED ISSUE #7367: MySQL and Inno DB updates
- [x]  MySQL 8 update
- [x]  InnoDB update

### LINKED ISSUE #7368: Laravel 9 update
- [x] Update to Laravel 9
- [x] Update packages

### LINKED ISSUE #7382: PHP 8.1 Update
Update to PHP 8.1

### PR DESCRIPTION
**Pull request by RafficMohammed**
resolves #7382
resolves #7368
resolves #7367 

### Requirements

- Php 8.1 support
- Mysql 8 support
- Innodb support

### CODE REVIEW

**Comment by RafficMohammed** [comment]
:information_source: Shift noticed you have additional namespaces in your application. You may use the [Consolidate Namespaces Shift](https://laravelshift.com/laravel-consolidate-custom-namespaces) to simplify your namespaces into the default Laravel `App` namespace.

**Comment by RafficMohammed** [comment]
:information_source: Laravel 9 moved the `resources/lang` folder to the top level of the project. While Shift moved and replaced references to this folder, you may have additional references to this folder which need to be updated.

**Comment by RafficMohammed** [comment]
:warning: In previous versions of Laravel, the `getSession` method returned an instance of `Illuminate\Session\Store`. In Laravel 9, `getSession` now returns a `Symfony\Component\HttpFoundation\Session\SessionInterface` implementation as the underlying Symfony method enforces this return type.

Should found potential uses of this method in the following files. You should review these instances to ensure your code is compatible with this type change.

- [ ] app/Http/Controllers/Admin/helpdesk/FormController.php

**Comment by RafficMohammed** [comment]
:warning: Laravel 9 upgraded to Flysystem 3.0 causing the behavior of the `Storage` facade to change slightly:

* Write operations (such as `put` and `write`) now overwrite existing files by default and return `false` instead of throwing an exception.
* Read operations (such as `get` and `download`) now return `null` instead of a `FileNotFoundException` when a file is missing.
* The `delete` operation now returns `true` even if the file did not exist.

For more details, you may review the [Flysystem 3.x](https://laravel.com/docs/9.x/upgrade#flysystem-3) section of the _Upgrade Guide_.

**Comment by RafficMohammed** [comment]
:warning: Laravel 9 transitioned from SwiftMailer to Symfony Mailer. While this transition should be relatively seamless and Shift automates any tedious changes, some changes may not reliably be automated.

**Dependencies**
Some mail providers may require an additional dependency. For example, if you are using Mailgun, then you will need to install the `symfony/mailgun-mailer` package:

```sh
composer require symfony/mailgun-mailer symfony/http-client
```

**Updated Return Types**
The `send`, `html`, `raw`, and `plain` methods now return an instance of `Illuminate\Mail\SentMessage`.

**Renamed "Swift" Methods and Classes**
Various SwiftMailer related methods and classes have been renamed to their Symfony Mailer counterparts. Shift renamed these for you, but depending on your usage, you may need to update your code for some changes in the APIs.

**Failed Recipients**
It is no longer possible to retrieve a list of failed recipients after sending a message. Instead, a `Symfony\Component\Mailer\Exception\TransportExceptionInterface` exception will be thrown if a message fails to send. Instead of relying on retrieving invalid email addresses after sending a message, it is recommend that you validate email addresses before sending the message instead.

For more details on what has changed you may review the [Symfony Mailer](https://laravel.com/docs/9.x/upgrade#symfony-mailer) section of the _Upgrade Guide_.

**Comment by RafficMohammed** [comment]
:x: Shift was unable to find some of your controllers and left them as string references in your routes.

You will need to search for the following controller names in your routes and replace them with the appropriate static `::class` reference manually.

- [ ] Admin\helpdesk\Label\LabelController

**Comment by RafficMohammed** [comment]
:warning: The `FILESYSTEM_DRIVER` environment variable was renamed to `FILESYSTEM_DISK` in Laravel 9. Shift attempted to [automate this change](https://github.com/ladybirdweb/faveo-helpdesk/pull/7695/commits/25d7fe64cb55f8f73d18faf26b806987ce9f2f39?w=1), but you should review any additional environment configuration and rename this variable.

**Comment by RafficMohammed** [comment]
:information_source: The `FILESYSTEM_CLOUD` environment variable was removed in a later release of Laravel 8. While you may still use the `cloud` disk, you are encouraged to [configure your own disks](https://laravel.com/docs/9.x/filesystem#configuration).

**Comment by RafficMohammed** [comment]
:warning: The `token` driver for API authentication is no longer available. This driver was not very robust and was removed from the documentation. Laravel now recommends using [Sanctum](https://laravel.com/docs/9.x/sanctum).

If you were using the `token` driver, you may re-add it within your `auth.php` configuration file then migrate to _Sanctum_ at your convenience.

**Comment by RafficMohammed** [comment]
:information_source: Shift [updated your dependencies](https://github.com/ladybirdweb/faveo-helpdesk/pull/7695/commits/927f9a4fa6e40508df84bfac492aee0797345780?w=1) for Laravel 9. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 9. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any Composer issues.

The following dependencies were updated by a major version and may have their own changes. You may check their changelog for any additional upgrade steps.

- [ ] [tymon/jwt-auth](https://packagist.org/packages/tymon/jwt-auth)

**Comment by RafficMohammed** [comment]
:information_source: Laravel 9 adopted [anonymous migrations](https://laravel-news.com/laravel-anonymous-migrations). Shift [automated this change](https://github.com/ladybirdweb/faveo-helpdesk/pull/7695/commits/8e812e3c5060ea80759600a609a9856ea8318821?w=1) to align with modern Laravel conventions and avoid naming migrations.

**Comment by RafficMohammed** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 6. If you are directly interacting with any Symfony component, you should review the [Symfony change log](https://github.com/symfony/symfony/blob/6.0/UPGRADE-6.0.md) for additional changes.

**Comment by RafficMohammed** [comment]
:information_source: The `app/Models` folder was reintroduced back in Laravel 8. This was an _optional_ change. Laravel and the `artisan` commands will automatically detect if you are using the `app/Models` folder or not.

If you wish to modernize your application to use the `app/Models` folder, you may run the [Namespace Models Shift](https://laravelshift.com/laravel-namespace-models) for free.

**Comment by RafficMohammed** [comment]
:information_source: Laravel 9 now uses Vite to build frontend assets. While you may continue to use Laravel Mix, it is no longer the default. If you wish to modernize your application to use Vite, you may run the [Vite Converter](https://laravelshift.com/convert-laravel-mix-to-vite) for free.

**Comment by RafficMohammed** [comment]
:tada: Congratulations, you're now running the latest version of Laravel!

Next, you may optionally run the following _Shifts_ to ensure your application is fully upgraded, adopts the latest Laravel conventions, and easier to maintain in the future:

- [Upgrade Checker](https://laravelshift.com/laravel-upgrade-checker) ensures your application is fully upgraded by detecting any outdated code.
- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automatically updates your code to the latest Laravel conventions.
- [Tests Generator](https://laravelshift.com/laravel-test-generator) intelligently generates model factories, HTTP Tests, and configuration for your application.
- [CI Generator](https://laravelshift.com/ci-generator) intelligently generates CI jobs to lint PHP, check code style, and run tests, including Dusk.

You may also use the [Shift Workbench](https://laravelshift.com/workbench) to automate common tasks for maintaining your Laravel and PHP applications.

**Review by priyadarshini2101 — COMMENTED** [review]
Found issues updated to Raffic.

https://docs.google.com/document/d/1ThvCk6_ZFkLQuDuoRh_gBbkm_59fjZBM5m9x0yOLuIs/edit?usp=sharing
Testing not completed..........

**Comment by Umasri-V** [comment]
Found issues updated to Raffic.
https://docs.google.com/document/d/1scJ2Zf2fGZ58sv6qVJc_YAVZjTkPMW8xWNr80pwUYjk/edit

**Comment by RafficMohammed** [comment]
@Umasri-V I fixed the issues. So please check and update me.

**Pull request merged**
