### PR TITLE
Mobile menu button -fix

### PR DESCRIPTION
**Pull request by Noor-mommadhi**
Mobile menu button doesn't work. It is fixed.

### CODE REVIEW

**Comment by Sabaric12** [comment]
Tested this PR with the fresh installation:-
Now After Fixing, we are able to click the mobile menu button, and we are able to click on any places where the search button is changed.
Before Fix
Screenshot from 2023-09-05 12-59-47
After Fix
Screenshot from 2023-09-05 13-06-09

**Review by Sabaric12 — DISMISSED** [review]

**Comment by Dhayanan** [comment]
Tested this PR fresh installation on Local:-
Second round test summary:-
Total time in days: 3 hours 
 Total issues: 12
 Minor - 8
Major - 4
Critical - 0
Functionality correction :-1
Issue document:-
https://docs.google.com/document/d/1AxlDsj0VXsKed_9xRlYqf6i8P48SJZJUSseS_WNJb9s/edit
Not checked for Agent and admin panel options are  not showing

**Comment by Noor-mommadhi** [comment]
@Dhayanan please create a separate issue for the Existing issues

**Comment by Dhayanan** [comment]
Tested this PR on existing DB on local:-
Second round test summary:-
Total time in days: 1.5 hours
 Total issues: 4
 Minor - 4
Major - 0
Critical - 0
Functionality correction :-1
**Before fix:-**
The  mobile view menu bar button is not clickable.
Master
**After fix:-**
Mentioned issues are fixed. It' s working.
In this branch,The mobile view menu bar button is  clickable.
mobile view

**Review by Dhayanan — APPROVED** [review]

**Pull request merged**
