### PR TITLE
Mobile menu button fix.

### PR DESCRIPTION
**Pull request by mucan54**
Mobile menu button doesn't work. It is fixed.

### CODE REVIEW

**Review by RafficMohammed — APPROVED** [review]

**Comment by RafficMohammed** [comment]
@Sabaric12 Check mobile menu icon in client panel

**Review by Sabaric12 — APPROVED** [review]
Tested this pr with fresh installation 
Now the Mobile Menu Button is showing in all the client and the admin and the agent Login all places it is working fine
Screenshot from 2023-06-19 12-23-02

**Comment by RafficMohammed** [comment]
@Sabaric12 Share here before fix icon

**Comment by bhanu2217** [comment]
**Demo Feedback:**

- @Noor-mommadhi Please check search button location in mobile view. Discuss with @Sakthi002

**Comment by Noor-mommadhi** [comment]
The alternate PR is 
https://github.com/ladybirdweb/faveo-helpdesk/pull/8216

**Pull request closed without merging**
