### PR TITLE
Api-fixes

### PR DESCRIPTION
**Pull request by Noor-mommadhi**
fixes-#8006

### CODE REVIEW

**Review by RafficMohammed — APPROVED** [review]

**Review by sowmiyasubramaniyan — APPROVED** [review]

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Last commits
image

Database-config API working fine getting response properly.
image
System-config API not working getting below response.
image
Once i put dd on handler showing below error.
image

**Review by SarfrazS — APPROVED** [review]
Tested Helpdesk Installation via API on server working fine.
image
image
image
image

Note:- On my local wamp server API installation not working.

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Both api executed and got success message after that when we hit url on browser getting below error once we click then it's working.
image

**Review by SarfrazS — APPROVED** [review]
Above issue will not come when we are below steps

1. Execute Database-config API
2. Execute System-config API
3. Run composer dumpautoload
4. Run Php artisan optimize:clear
image

**Pull request merged**
