### PR TITLE
Arabic language added 

### PR DESCRIPTION
**Pull request by Noor-mommadhi**
Current PR will have this closed PR : - https://github.com/ladybirdweb/faveo-helpdesk/pull/8202 code and functionality will complete remaining functionality corrections 
https://docs.google.com/document/d/1dlr6eRTl6fmlNXbYsc0QyjjKncYxsJkYc6LeBOCuxs8/edit

### CODE REVIEW

**Comment by KNaveenraj-ladybird** [comment]
Refer this document for updated corrections https://docs.google.com/document/d/1dlr6eRTl6fmlNXbYsc0QyjjKncYxsJkYc6LeBOCuxs8/edit

**Review by RafficMohammed — APPROVED** [review]

**Comment by AbishekChinnaraju** [comment]
@KNaveenraj-ladybird, Please get Demo approve.

**Comment by Sabaric12** [comment]
Tested this PR with the existing instance 
Some of the mentioned issues are not fixed the issue sheet is mentioned below
https://docs.google.com/document/d/1rYuluXOxNjPDGX8_spXljeOdyuA1Av45FaSrR7ALENg/edit
Round 1: Testing Summary
Total time in days: 3 hours
Total issues: 13
Minor - 4
Major - 5 
Critical - 4
No of times PR was sent for Functionality correction:1
PR breaks existing functionality: No

**Comment by Sabaric12** [comment]
Tested this PR with the existing instance
The mentioned issues are working fine 
Round 1: Testing Summary
Total time in days: 3 hours
Total issues: 0
Minor - 0
Major - 0
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality: No
Note:
Some of the existing issues are created
https://github.com/ladybirdweb/faveo-helpdesk/issues/8250
https://github.com/ladybirdweb/faveo-helpdesk/issues/8252

**Review by Sabaric12 — APPROVED** [review]

**Comment by AbishekChinnaraju** [comment]
Tested this PR with the existing server instance instance
**Secon Round Testing Summary:**
Total time in days: 1 hours
Total issues: 0
Minor - 0
Major - 0
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality: No
**Note:**
I found some issues and created them separately.

**Review by AbishekChinnaraju — APPROVED** [review]

**Comment by KNaveenraj-ladybird** [comment]
Hello ladybirdweb/faveo-helpdeskThank you for contacting us. This is an automated response confirming the receipt of your ticket. Our team will get back to you as soon as possible. When replying, please make sure that the ticket ID is kept in the subject so that we can track your replies.Ticket ID: AAAA-0000-0004  You can check the status of or update this ticket online at: https://localhost/faveo-helpdesk/public/check_ticket/eyJpdiI6IjZ3ZTVNNjYzMDNQTXdaYWcwd2N1NUE9PSIsInZhbHVlIjoiMkNpNUZzY3BSS0hibHREQndoV0lsdz09IiwibWFjIjoiY2U0NjM0Zjc4MDY0ZDJiNTVjMWRkOTRmMzE2ZmVjNWQzMGIwNmE4MzQ5ZDdkZjI4NGIxNDAzNDg5M2RlNjY4MyIsInRhZyI6IiJ9

**Comment by KNaveenraj-ladybird** [comment]
---Reply above this line--- Hello ***@***.***,A reply been made to ticket AAAA-0000-0004FromName: NaveenrajE-mail: ***@***.*** Hello Naveenraj,New ticket AAAA-0000-0004created FromName: ladybirdweb/faveo-helpdesk   E-mail: ***@***.*** 
Merged #8245 into development.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ladybirdweb/faveo-helpdesk/pull/8245#event-10776268718",
"url": "https://github.com/ladybirdweb/faveo-helpdesk/pull/8245#event-10776268718",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]Kind Regards, Support Center
Kind Regards, Support Center

**Pull request merged**
