### PR TITLE
Admin LTE Theme Upgrade

### PR DESCRIPTION
**Pull request by Noor-mommadhi**
Updated the Admin LTE theme latest version (3.2.0)#3418.
This P.R doesn't include client panel theme update.

### CODE REVIEW

**Comment by bhanu2217** [comment]
Are both client panel and agent/admin panel themes updated in this P.R?

**Comment by bhanu2217** [comment]
Please link issue no in the sidebar under development.

**Comment by bhanu2217** [comment]
> Updated the theme latest version (3.2.0)#3418

I think only admin/agent panel theme is updated here.
The issue talks here about updating client panel also https://github.com/ladybirdweb/faveo-helpdesk/issues/3418

**Review by RafficMohammed — APPROVED** [review]

**Review by sowmiyasubramaniyan — APPROVED** [review]

**Comment by Dhayanan** [comment]
Test with this PR for fresh installation:-
Found the issues   document shared below in the link:-

**Review by Sabaric12 — CHANGES_REQUESTED** [review]
**Testing Not Completed this pr till now** 
These many Issues I have found and shown to the developer
**This below link is for the issues document**
https://docs.google.com/spreadsheets/d/1-mjDmuB1QUbLh8LsBhs326eshnuIM63AwD0hBLsj8IQ/edit?pli=1#gid=1739301425

**Comment by RafficMohammed** [comment]
Rebase from development branch

**Review by Sabaric12 — APPROVED** [review]
While Testing this Pr with the Fresh and Existing installation The Agent Panel Pointed issues are working fine now

**Comment by Dhayanan** [comment]
**Tested with this Pr on fresh installation:-**
Checked for admin panel , pointed issue is fixed and  it's working fine.

**Review by Dhayanan — APPROVED** [review]

**Comment by Sabaric12** [comment]
Tested this pr with fresh installation 
Admin Panel I tested all the pointed issues  are working fine

**Comment by Dhayanan** [comment]
Tested for this PR :- 
I checked the agent panel, Mention pointed issues is fixed. It working.

**Pull request merged**
