### PR TITLE
Arabic language added

### PR DESCRIPTION
**Pull request by mucan54**
Arabic language added

### CODE REVIEW

**Review by RafficMohammed — APPROVED** [review]

**Review by Sabaric12 — APPROVED** [review]
Tested this pr with the fresh installation
Now the new Language named as arabic as added
Before Fix
Screenshot from 2023-06-19 16-40-04
After Fix
Screenshot from 2023-06-19 16-40-53

**Comment by bhanu2217** [comment]
**Demo feedback:**

- RTL not working. @Noor-mommadhi Please talk to @Sakthi002 and fix this.
- @Noor-mommadhi also discuss with @Sakthi002 and test all button color change is working as expected

**Comment by Dhayanan** [comment]
Tested this PR existing  DB on local :-
Second round test summary:-
Total time in days:  6  hours
 Total issues: 44
 Minor - 44
Major - 0
Critical - 0
Functionality correction :-1
Issue document:-
https://docs.google.com/document/d/1dlr6eRTl6fmlNXbYsc0QyjjKncYxsJkYc6LeBOCuxs8/edit

**Comment by KNaveenraj-ladybird** [comment]
Further changes and functionality corrections would be done in this PR: -  https://github.com/ladybirdweb/faveo-helpdesk/pull/8245 . So i am closing this pr

**Pull request closed without merging**
