### PR TITLE
Fixed IMAP and exchange error, added option to cron for withoutoverlapping updated dependencie

### PR DESCRIPTION
**Pull request by JelleDijkhuizen**
With this PR i tried to fix a few bug.

First is IMAP error when using exchange. This fix was easy just updated tedivm/fetch to the latsted version and made a change to the fecht command to mark the emails as seen.

Second i added an option to the cronjobs to run without overlapping. I did this to make sure the fetch command doesn't run twice and make double tickets.

Small changes: ran composer update to update the depenencies to newer versions and added a wysisyg editor to some admin fields.

### CODE REVIEW

**Comment by kustav123** [comment]
HI ,
A facing some issue with connecting to my in house  exchange server . am gating 
Connection could not be established with host 172.16.16.5 [ #0]
 error.  I have tried to connect via SMTP and POP3 over SSL .

**Comment by kustav123** [comment]
Capture1
Capture
Can someone help my regurding this exchange server issue |?

**Comment by Dijkma** [comment]
@kustav123 you need to connect via IMAP not POP

**Comment by bhanu2217** [comment]
We have just made the release for v.2.0.0. Can you please rebase this P.R

**Pull request closed without merging**
