### PR TITLE
remove 500 error on `all pages` admin page

### PR DESCRIPTION
**Pull request by kaigorodov2015**

### CODE REVIEW

**Comment by SarfrazS** [comment]
Hi kaigorodov2015,

I have gone over the issue you have mentioned.
Please go to root of directory where Faveo is installed and in the root folder open config/app.php file  and  change  'debug' => false to  'debug' => true , save it  and run the installer again. Send me the exact error message that you see this time on the screen, so that i can provide proper fix for this issue.
Thank You.

**Comment by kaigorodov2015** [comment]
The issue is already fixed. Look at the commit/file in the pull request.

**Comment by sujit223** [comment]
The issue is on every push this thing changes back to a single line. Not sure what exactly is the issue.

**Comment by kaigorodov2015** [comment]
class TicketController not found in PageController on ajax call to get all pages in admin area Knowledge base -> All pages.

**Comment by sujit223** [comment]
please send me URL

**Comment by sujit223** [comment]
If the controller is using this use App\Http\Controllers\Agent\helpdesk\TicketController;  then it should not throw any exception

**Comment by sujit223** [comment]
Let me check and update

**Comment by sujit223** [comment]
I tried the same path it works fine. Please let us know if you are still facing the issue

**Pull request merged**
