### PR TITLE
Community :: Bootstrap4 and AdminLTE 3 Updation

### LINKED ISSUE #4372: Update Bootstrap and AdminLTE theme

### PR DESCRIPTION
**Pull request by Sakthi002**
Fixes #4372

### CODE REVIEW

**Review by shruti376 — CHANGES_REQUESTED** [review]
Issues
- [ ] Create/Edit Agent not working
- [ ] Create ticket option not showing in agent panel , so not able to check the dependencies of it like workflow, sla
Once this fixed will continue the testing. Please check the below document for issues
https://docs.google.com/document/d/1lObdgBgeb0BGKNif6Uz3i9oZzBzElVBHWD3IJrbVCEA/edit

**Comment by shruti376** [comment]
Please check the above updated sheet for issues

**Review by shruti376 — COMMENTED** [review]
Retested all issues. All are fixed except Change language to french, Portugesee, Brazalian porteguese, in client panel search option coming down. For spanish it's working now but for above languages it's showing the same. Please check once and let me know

**Comment by Sakthi002** [comment]
> Retested all issues. All are fixed except Change language to french, Portugesee, Brazalian porteguese, in client panel search option coming down. For spanish it's working now but for above languages it's showing the same. Please check once and let me know

FIxed @shruti376

**Review by shruti376 — APPROVED** [review]
All pointed issues are fixed now
Last commit
Screenshot_134

**Review by mverma16 — APPROVED** [review]

**Pull request merged**
