### PR TITLE
Client Panel theme update

### LINKED ISSUE #8118: Client Panel theme update
Client Panel template is available here https://github.com/ladybirdweb/faveo-helpdesk/issues/3418
Our client panel template now also has support for Bootstrap 5.

For now use Bootstrap 4 template for client panel as Admin LTE currently doesn't support Bootstrap 5.

### PR DESCRIPTION
**Pull request by Noor-mommadhi**
upgrade the client panel
Fixes #8118

### CODE REVIEW

**Review by Sabaric12 — COMMENTED** [review]
While Checking this pr with existing installation
The issue link is given below
https://docs.google.com/spreadsheets/d/1-mjDmuB1QUbLh8LsBhs326eshnuIM63AwD0hBLsj8IQ/edit#gid=942253032

**Review by Sabaric12 — APPROVED** [review]
Testing this pr with the existing installation
The Pointed issues are working fine now

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Please remove this toggle from client panel there is no use case. Functionality is not working if we changed theme.
Dashboard

On the edge browser password icon is overlapping please check and fix it. On master working fine.
image

**Comment by Sabaric12** [comment]
While Viewing the ticket with the attachment we click on that I am getting the 500 server error
Screenshot from 2023-06-05 17-44-31

**Comment by Dhayanan** [comment]
Tested this PR fresh insatallation on server:-
1. while searching the article name , it throws 500 error page.
image
2. footer and social widgets ui is breaking.
image

**Comment by Noor-mommadhi** [comment]
@Sabaric12 @Dhayanan mentioned issues are fixed please check

**Review by SarfrazS — APPROVED** [review]
We created a separate issue for bulk change status from my ticket data table. Rest three pointed issues fixed.
https://github.com/ladybirdweb/faveo-helpdesk/issues/8180

**Pull request merged**
