### PR TITLE
Bug fix

### LINKED ISSUE #7827: Faveo Helpdesk has SQL injection vulnerability
I don't know which version of SQL injection vulnerability exists, but I found that there are SQL injection vulnerabilities in thousands of IP addresses on the cyberspace mapping platform.
When logging in, the email account xxx@xx.xx After that, add ', there are SQL statement errors, which will lead to SQL injection vulnerability.
Use the Burpsuite network packet capturing tool to capture the POST data packets when users log in, and use the Sqlmap tool for SQL injection.
As this picture show：

### PR DESCRIPTION
**Pull request by Noor-mommadhi**
fixes #7827

### CODE REVIEW

**Review by SarfrazS — CHANGES_REQUESTED** [review]
last commit
image

The alert message not showing properly.
image

**Comment by Noor-mommadhi** [comment]
I rebase my branch please check

**Review by sowmiyasubramaniyan — APPROVED** [review]

**Review by SarfrazS — APPROVED** [review]
Before Fix:-
image

image

After Fix:-
image

**Comment by RafficMohammed** [comment]
@Noor-mommadhi Squash commits

**Pull request merged**
