### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by manojnegee**
/vendor directory is included to exclude it from commit.

### CODE REVIEW

**Comment by manojnegii90** [comment]
Sorry for the late response , I was a little busy.

I don't think so. you can mention them to run "composer install" in case you need to update the composer. 
Anyone who can install this project first time or can pull the updates or changes, can be expected to run "composer install" command.

Currently, If I make changes in composer file or run "composer udpate" instead of "composer install" to be updated with current versions as per my needs and later, I try to fetch the updated code from your repo, it creates a lot of conflicts in the vendor file makes it difficult to get the latest code from your repo.

**Comment by mverma16** [comment]
Many of our end users download zip file of a code from release tags and our website which is linked with our repository. 
Also there are certain packages which we have customized according to our need and if users run composer update those packages will get update with the latest version(if updates for package are available) which can break our application. 
As many packages are now being updated with Laravel 5.4 we are also planning to update our system but that will take some time.
We know it's a good practice to add our dependencies directory(which is vendor in our case) in `.gitignore` and allow users/developers to run composer update to include any dependencies in their system. But I don't think it's currently possible for our system. Still I'll put this on the table to discuss in our team.

**Comment by manojnegii90** [comment]
ok but you shouldn't made changes directly in vendor folder. Its better to create your own package or class separately that can extend those functionalities that you want to change or customize.

**Comment by andrew-za** [comment]
As mentioned one should never make changes directly to vendor packages. You are able to Fork the vendors source then make your own changes in your fork.
Then in your composer.json you are able to select your forks branch.

**Comment by mverma16** [comment]
@manojnegii90 , @andrew-za this seems to be a good suggestion, we'll try to practice this approach in our development.
We are a team made of bunch of newbies, I am sure we've a long way to go and learn new things. This community will help us to learn and grow our skills and product.

**Comment by mathieu-aubin** [comment]
@mverma16 -- something i remember talking to you about a while back, glad to see it moving forward. Using the package manager as intended will not only greatly reduce overall app distribution size (faveo is just so huge), will also ensure the deps are current while removing (or at least partially) the burden of maintaining/keeping track of files you technically wouldn't have to, but most of all, will help faveo become fully redistribuable.

**Comment by Phaniraj35** [comment]
@RafficMohammed There were some changes in vendor directory.
If this PR is merged, dependant functionality will be broken.
Ensure those changes are handled using new packages or extending classes before approving this.

**Comment by RafficMohammed** [comment]
@Phaniraj35 Bro, I hope, we can ignore these changes. Coz, Upcoming days, we are gonna make a release for laravel 9 upgrade. These changes can affect there also.

**Comment by bhanu2217** [comment]
We have just made the release for v.2.0.0. Can you please rebase this P.R

**Pull request closed without merging**
